# Generated by Django 6.1.1 on 2026-09-27 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Kuupäev')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Algusaeg')),
                ('intensity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Tugevus')),
                ('is_pulsating', models.BooleanField(default=False, verbose_name='Pulseeriv/tuksuv')),
                ('is_dull_pressing', models.BooleanField(default=False, verbose_name='Tuim/suruv')),
                ('is_unilateral', models.BooleanField(default=False, verbose_name='Ühepoolne')),
                ('is_bilateral', models.BooleanField(default=False, verbose_name='Kahepoolne')),
                ('is_occipital', models.BooleanField(default=False, verbose_name='Kuklas')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kestus')),
                ('nausea', models.BooleanField(default=False, verbose_name='Iiveldus')),
                ('vomiting', models.BooleanField(default=False, verbose_name='Oksendamine')),
                ('photophobia', models.BooleanField(default=False, verbose_name='Valguskartus')),
                ('phonophobia', models.BooleanField(default=False, verbose_name='Mürakartus')),
                ('exertion_intolerance', models.BooleanField(default=False, verbose_name='Pingutuse talumatus')),
                ('visual_disturbance', models.BooleanField(default=False, verbose_name='Nägemishäire')),
                ('speech_disturbance', models.BooleanField(default=False, verbose_name='Kõnehäire')),
                ('sensory_disturbance', models.BooleanField(default=False, verbose_name='Tundehäired')),
                ('other_symptoms', models.CharField(blank=True, max_length=255, verbose_name='Muud tunnused')),
                ('trigger_factor', models.CharField(blank=True, max_length=255, verbose_name='Vallandav faktor')),
                ('medication_name', models.CharField(blank=True, max_length=100, verbose_name='Ravimi nimi')),
                ('dose_mg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kogus')),
                ('was_effective', models.BooleanField(blank=True, null=True, verbose_name='Mõju')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headache_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kasutaja')),
            ],
            options={
                'verbose_name': 'Headache entry',
                'verbose_name_plural': 'Headache entries',
                'ordering': ['-date', '-start_time', '-id'],
            },
        ),
    ]
