"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Railway sets RAILWAY_ENVIRONMENT_NAME on every deploy; locally it's absent.
ON_RAILWAY = 'RAILWAY_ENVIRONMENT_NAME' in os.environ


def env_list(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q4yfu@h$gzpm-j-3_7fhcwpyz5n6c8p^y!a-i#)^3-3=^8+31i',
)

# Debug is on locally and off on Railway unless DJANGO_DEBUG says otherwise.
DEBUG = os.environ.get('DJANGO_DEBUG', '0' if ON_RAILWAY else '1') == '1'

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Railway's generated (or custom) domain, so there's nothing to configure by hand
if public_domain := os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(public_domain)
    CSRF_TRUSTED_ORIGINS.append(f'https://{public_domain}')

if not DEBUG:
    # The fallback key above is public (it's in the repo): never run production on it.
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when DJANGO_DEBUG=0.')

    # Railway terminates TLS and forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SILENCED_SYSTEM_CHECKS = [
        'mail.E001',       # the app never sends email (no sign-up, no password reset)
        'security.W005',   # HSTS includeSubDomains: not ours to decide on *.up.railway.app
        'security.W021',   # HSTS preload: same; opt in once on a custom domain
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'a_tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite, kept on a Railway volume in production. The file lives at, in order:
# SQLITE_PATH, the attached volume, or the project folder (local dev).
if os.environ.get('SQLITE_PATH'):
    SQLITE_PATH = Path(os.environ['SQLITE_PATH'])
elif os.environ.get('RAILWAY_VOLUME_MOUNT_PATH'):
    SQLITE_PATH = Path(os.environ['RAILWAY_VOLUME_MOUNT_PATH']) / 'db.sqlite3'
else:
    SQLITE_PATH = BASE_DIR / 'db.sqlite3'

if ON_RAILWAY and not DEBUG and SQLITE_PATH.is_relative_to(BASE_DIR):
    # Without a volume the database would be wiped on every deploy.
    raise ImproperlyConfigured('Attach a Railway volume (or set SQLITE_PATH) so the diary survives redeploys.')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_PATH,
        'OPTIONS': {
            # Sensible production SQLite: WAL lets reads and a write overlap,
            # IMMEDIATE avoids "database is locked" upgrades between workers.
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            'transaction_mode': 'IMMEDIATE',
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'et'

TIME_ZONE = 'Europe/Tallinn'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise serves static files straight from the app folders, so a deploy
# needs no collectstatic step (Railpack's default start command doesn't run one).
WHITENOISE_USE_FINDERS = True


# Auth
# Everything requires login (LoginRequiredMiddleware); the session lasts a year
# so she only has to log in once per device.

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'entry_list'
LOGOUT_REDIRECT_URL = 'login'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365


# Logging: errors to stdout, where Railway collects them

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
